---
- file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ cloud_network_interconnect_output_dir }}"
    - "{{ cloud_network_interconnect_output_dir }}/host_vars"
    - "{{ cloud_network_interconnect_output_dir }}/group_vars"
