---

- name: Include responder role deprovision tasks
  include_role:
    name: "{{ cloud_vpn_responder_provisioner_role }}"
    tasks_from: "cloud_vpn/deprovision_responder"
    defaults_from: "cloud_vpn/provisioners/{{ cloud_vpn_responder_provisioner }}/responder.yaml"
