---

- name: Load initiator provider defaults
  include_role:
    name: "{{ cloud_vpn_initiator_provider_role }}"
    defaults_from: "cloud_vpn/providers/{{ cloud_vpn_initiator_provider }}/initiator"
    tasks_from: "cloud_vpn/noop"
    public: true
