---

- include_tasks: "{{ cloud_vpn_initiator_type }}/initiator/provision.yaml"

- include_tasks: "{{ cloud_vpn_responder_type }}/responder/provision.yaml"

- include_tasks: "{{ cloud_vpn_responder_type }}/responder/configure.yaml"

- include_tasks: "{{ cloud_vpn_initiator_type }}/initiator/configure.yaml"
