---

- name: Install required pip packages
  include_tasks: install_pip_requirements.yaml
  when: cloud_vpn_install_pip_requirements

- name: Include create VPN tasks
  include_tasks: create_vpn.yaml
  when: cloud_vpn_state == 'present'

- name: Include delete VPN tasks
  include_tasks: delete_vpn.yaml
  when: cloud_vpn_state == 'absent'
