---

- template:
    src: openstack_vyos/initiator/provision.j2
    dest: "/tmp/{{ cloud_vpn_name }}-initiator-provision.template"

- os_stack:
    cloud: "{{ cloud_vpn_initiator_openstack_cloud }}"
    name: "{{ cloud_vpn_name }}-initiator-stack"
    template: "/tmp/{{ cloud_vpn_name }}-initiator-provision.template"

- os_server_facts:
    cloud: rdo-cloud
    server: "{{ cloud_vpn_name }}-initiator-instance"
  register: out

- set_fact:
    cloud_vpn_initiator_ip: "{{ openstack_servers[0]['interface_ip'] }}"
