---
- add_host:
    name: initiator
    ansible_host: "{{ cloud_vpn_initiator_ip }}"
    ansible_user: "{{ cloud_vpn_initiator_user }}"
    ansible_connection: network_cli
    ansible_network_os: ios

- ios_config:
    src: "ios/initiator/{{ cloud_vpn_responder_type }}/config.j2"
  delegate_to: initiator
