---

- template:
    src: openstack_vyos/responder/provision.j2
    dest: "/tmp/{{ cloud_vpn_name }}-responder-provision.template"

- os_stack:
    cloud: "{{ cloud_vpn_responder_openstack_cloud }}"
    name: "{{ cloud_vpn_name }}-responder-stack"
    template: "/tmp/{{ cloud_vpn_name }}-responder-provision.template"

- os_server_facts:
    cloud: rdo-cloud
    server: "{{ cloud_vpn_name }}-responder-instance"
  register: out

- set_fact:
    cloud_vpn_responder_ip: "{{ openstack_servers[0]['interface_ip'] }}"
