---
- name: Create Ansible runner settings file
  template:
    src: two_step/ansible_runner/settings
    dest: "{{ cloud_vpn_output_dir }}/env/settings"

- name: Create Ansible runner extravars file
  template:
    src: two_step/ansible_runner/extravars
    dest: "{{ cloud_vpn_output_dir }}/env/extravars"
